# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veg_name', models.CharField(max_length=16, verbose_name='蔬菜名')),
                ('lowest_price', models.IntegerField(verbose_name='最低价格')),
                ('avg_price', models.IntegerField(verbose_name='平均价格')),
                ('highest_price', models.IntegerField(verbose_name='最高价格')),
                ('created_at', models.DateField(auto_now=True, verbose_name='日期')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(db_index=True, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veg_name', models.CharField(db_index=True, max_length=16, verbose_name='蔬菜名')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='veg_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Unit', verbose_name='规格'),
        ),
        migrations.AddField(
            model_name='record',
            name='vegetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Vegetable', verbose_name='所属蔬菜'),
        ),
    ]
