# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='recorded_at',
            field=models.DateField(auto_now=True, verbose_name='记录日期'),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='type_name',
            field=models.CharField(db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='record',
            name='created_at',
            field=models.DateField(auto_now=True, verbose_name='创建日期'),
        ),
    ]
