# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20160929_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='veg_type',
        ),
        migrations.AddField(
            model_name='vegetable',
            name='veg_type',
            field=models.CharField(choices=[('n', '普通'), ('w', '水菜')], default='n', max_length=1),
        ),
    ]
