# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20161013_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='item_name',
            field=models.CharField(db_index=True, default='', max_length=16, verbose_name='物品名'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('item_name', 'item_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together=set([('item', 'recorded_at')]),
        ),
    ]
