# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20161013_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='record',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='创建日期'),
        ),
    ]
