# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20160929_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='veg_name',
        ),
    ]
