# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_remove_record_veg_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='veg_name',
            field=models.CharField(default='', max_length=16, verbose_name='蔬菜名'),
        ),
    ]
