# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20161016_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='recorded_at',
            field=models.DateField(verbose_name='记录日期'),
        ),
    ]
