# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_record_veg_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VegType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='vegetable',
            name='veg_unit',
            field=models.CharField(choices=[('n', '普通'), ('w', '水菜')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='vegetable',
            name='veg_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.models.ItemType', verbose_name='所属类型'),
        ),
    ]
