# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20161017_1046'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='record',
            unique_together=set([('item', 'recorded_at')]),
        ),
    ]
