# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20161011_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetable',
            name='created_at',
            field=models.DateField(auto_now=True, verbose_name='创建日期'),
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together=set([('vegetable', 'created_at')]),
        ),
        migrations.AlterUniqueTogether(
            name='vegetable',
            unique_together=set([('veg_name', 'veg_unit', 'veg_type')]),
        ),
    ]
